Page sorry
epfl-idevelop/elements pull request #628
Opened 2023-01-26 10:28 UTC by williambelle

2023-01-27 09:14 UTC, xentenza commented on assets/components/pages/sorry/sorry.twig
> +  <header class="page-header justify-content-xl-between align-items-xl-center mb-5">
Normalement:
- il ne devrait y avoir qu'une balise <h1> par page (balise de titre principal);
- les balises <hn> ne sont pas faites pour travailler la cosmétique d'une page, mais pour structurer un contenu.

2023-01-27 10:53 UTC, alinekeller requested changes

2023-01-27 10:53 UTC, alinekeller commented on assets/components/pages/sorry/sorry.twig
> +  <header class="page-header justify-content-xl-between align-items-xl-center mb-5">
L'utilisation de deux balises `<h1>` dans ce cas de figure peut être justifié, même si ce n'est effectivement pas idéal.

Ca ne me semble toutefois pas terrible non plus de réunir les deux titres dans une seule balise `<h1>`, ça donnerait un titre bizarre en deux langues, pas top ni pour le référencement, ni pour les lecteurs d'écran. Pour l'accessibilité on peut en revanche ajouter l'attribut 'lang' afin de préciser la langue de chaque titre:

```
<h1 class="mb-4" lang="fr">Le site est actuellement indisponible</h1>
<h1 class="mb-4" lang="en">The site is currently unavailable</h1>
```

En revanche je rejoins la remarque d'Adrian concernant les deux `<h4>` qui ne devraient pas du tout être utilisés à cet endroit: ça n'a pas de sens d'un point de vue sémantique, un `<h4>` doit suivre un `<h3>`, pas un `<h1>`. Si le but est uniquement d'appliquer le style visuel d'un titre de niveau 4, il est possible d'appliquer la classe "h4" sur n'importe quel élément de texte. Ca donnerait donc:

```
<p class="h4" lang="fr">Veuillez réessayer plus tard.</p>
<p class="h4" lang="en">Please try again later.</p>
```

2023-02-07 14:28 UTC, xentenza approved these changes

2023-02-07 14:28 UTC, xentenza commented on assets/components/pages/sorry/sorry.twig
> +</div>
<div class="container px-5 px-xxl-6 mt-5">
```suggestion
<div class="container px-5 px-xxl-6 mt-5">
  <header class="page-header justify-content-xl-between align-items-xl-center mb-5">
    <h1 class="mb-4">Le site est actuellement indisponible</h1>
    <h1 class="mb-4">The site is currently unavailable</h1>
  </header>
  <h4>
    Veuillez réessayer plus tard.
  </h4>
  <h4>
    Please try again later.
  </h4>
</div>
```
  <header class="page-header justify-content-xl-between align-items-xl-center mb-5">
    <h1 class="mb-4">Maintenance</h1>
  </header>
  <p>Malheureusement, le site est actuellement indisponible.<br>Veuillez réessayer plus tard.</p>
  <p>Unfortunately, the site is currently unavailable.<br>Please try again later.</p>
</div>

2023-02-09 16:00 UTC, williambelle commented on assets/components/pages/sorry/sorry.twig
> +</div>
Il me semble que la suggesstion est obsolète. Le texte a été complétement modifié le 3 février (https://github.com/epfl-si/elements/commit/888da4b7f13db2514806478e28bea1695556d257) selon tes remarques du meeting.
La page est comme ça maintenant :

![Screenshot from 2023-02-09 16-54-33](https://user-images.githubusercontent.com/2843501/217865925-64730b29-d4fe-43df-821f-eeb8c00329bc.png)

2023-02-09 16:05 UTC, alinekeller approved these changes

2023-02-23 16:03 UTC, merged