New social icons
epfl-idevelop/elements pull request #683
Opened 2023-09-29 07:59 UTC by xentenza

- added TikTok
- added Mastodon
- social-color.scss in alphabetical order

2023-09-29 10:42 UTC, alinekeller requested changes
Les couleurs définies dans le fichier social-colors.scss ne sont pas appliquées sur les icônes de Mastodon et Tiktok:

<img width="451" alt="" src="https://github.com/epfl-si/elements/assets/6631947/6d3a67b4-1b1d-4840-a308-e6ab3b1b6a75">

Il faut ajouter les styles suivants dans le fichier atoms/social-icon/social-icon.scss (vers la ligne 90, après les styles déjà définis pour les autres icônes):

```
.social-icon-mastodon {
  background-color: $mastodon;
}

.social-icon-tiktok {
  background-color: $tiktok;
}
```

2023-10-03 12:58 UTC, williambelle commented on assets/components/atoms/social-icon/social-icon.scss
> +  background-color: $tiktok;
Le logo TikTok me semble minuscule comparé aux autres:
![Screenshot from 2023-10-03 14-44-23](https://github.com/epfl-si/elements/assets/2843501/7a39a749-80a7-40f5-b1db-077f184308a7)

On pourrait augmenter la taille de 1.3 comme YouTube ?

2023-10-05 12:06 UTC, xentenza commented on assets/components/atoms/social-icon/social-icon.scss
> +  background-color: $tiktok;
Ce sont les fichiers de base fournis par les TikTok Brand Guidelines. Mais bonne idée, c'est modifié dans ma nouvelle PR

2023-10-05 14:49 UTC, alinekeller approved these changes

2023-10-05 15:16 UTC, williambelle approved these changes

2023-10-05 15:19 UTC, merged