New Sponsor List organism
epfl-idevelop/elements pull request #753
Opened 2024-09-10 09:59 UTC by xentenza

- new organism: "Sponsor List"
- new picture for molecules/sponsors

2024-09-26 14:28 UTC, williambelle approved these changes

2024-10-22 10:10 UTC, alinekeller requested changes

2024-10-22 10:10 UTC, alinekeller commented on assets/components/molecules/sponsor/sponsor.twig
Même remarque concernant l'attribut ALT.

2024-10-22 10:10 UTC, alinekeller commented on assets/components/molecules/sponsor/sponsor-link.twig
Le contenu de l'attribut ALT devrait reprendre le texte présent sur le logo, pas indiquer "Sponsor". Ici par exemple juste "EPFL".

2024-10-30 16:29 UTC, alinekeller approved these changes

2024-10-31 07:52 UTC, williambelle approved these changes

2024-10-31 07:54 UTC, merged