New "canard" button
epfl-idevelop/elements pull request #758
Opened 2024-10-21 08:18 UTC by xentenza

An additional colour for the buttons, based on the graphic charter of the EPFL; red is sometimes perceived as "too aggressive".

2024-10-22 12:41 UTC, alinekeller requested changes
La couleur $leman n'a pas un contraste suffisant avec le texte blanc ([voir le tableau dans le styleguide](https://epfl-si.github.io/elements/#/colors)). Il faudrait soit utiliser la couleur $canard qui est ok, soit définir une variante $leman-dark qui aurait un contraste suffisant avec le blanc. Par exemple la teinte #00827C serait ok.

2024-10-30 09:11 UTC, xentenza commented
> La couleur $leman n'a pas un contraste suffisant avec le texte blanc ([voir le tableau dans le styleguide](https://epfl-si.github.io/elements/#/colors)). Il faudrait soit utiliser la couleur $canard qui est ok, soit définir une variante $leman-dark qui aurait un contraste suffisant avec le blanc. Par exemple la teinte #00827C serait ok.

Caramba, comment ais-je pu oublier de vérifier ça? 🫣

Merci. Partons alors sur la couleur $canard. J'ai également défini une variante $canard-dark (spéciale Haloween) avec une teinte #004248. N'hésite pas à proposer mieux!

2024-10-30 16:47 UTC, alinekeller approved these changes

2024-10-30 16:49 UTC, alinekeller commented
> Caramba, comment ais-je pu oublier de vérifier ça? 🫣
> 
> Merci. Partons alors sur la couleur $canard. J'ai également défini une variante $canard-dark (spéciale Haloween) avec une teinte #004248. N'hésite pas à proposer mieux!

C'est parfait ! Je valide la couleur canard de Halloween 😄
Je l'ai ajoutée dans le fichier colors.json afin qu'elle apparaisse dans la liste sur la page "Colors" du styleguide.

2024-10-31 12:06 UTC, williambelle approved these changes

2024-10-31 12:09 UTC, merged